name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: ['14', '>=16']

    name: ${{ matrix.platform }} / Node.js v${{ matrix.node-version }}
    runs-on: ${{ matrix.platform }}
    steps:
    - run: git config --global core.autocrlf false  # Preserve line endings
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm ci
        npm run test:ci
      env:
        CI: true

  build_all:
    if: always()
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check build matrix status
        if: ${{ needs.build.result != 'success' }}
        run: exit 1
